"""Topic Added

Revision ID: 302d6d33d083
Revises: 383df8a77fa0
Create Date: 2026-05-28 06:06:30.659684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302d6d33d083'
down_revision: Union[str, Sequence[str], None] = '383df8a77fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptiontasks', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptiontasks', 'topic')
    # ### end Alembic commands ###
