"""and another

Revision ID: 383df8a77fa0
Revises: 1a6aff23258c
Create Date: 2026-05-28 02:16:15.235190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383df8a77fa0'
down_revision: Union[str, Sequence[str], None] = '1a6aff23258c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptiontasks', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptiontasks', 'display_name')
    # ### end Alembic commands ###
